### ISSUE TITLE
原版加了个4chan版本（好像去了关键词数），能更新一下吗？谢谢

### ISSUE THREAD

**Issue by VoidxHoshi** [physics1024/Stable-Diffusion-adapted-to-NovelAI-for-kaggle#1]
以及要不然加个验证来防爬虫

**Comment by physics1024** [comment]
好的。您说的爬虫是pickle中的恶意字符串还是爬gradio链接的爬虫？如果是pickle，kaggle不支持读写.cache目录所以验证会报错，这个没办法解决。gradio的话倒是可以通过设置用户名密码来避免其他人访问。

**Comment by physics1024** [comment]
已添加NAIFU，不过尚未测试可行性（不知怎的kaggle网速太慢）。
添加gradio用设置户选项。

**Comment by physics1024** [comment]
试着把“!bash run.sh & cloudflared tunnel --url localhost:6969”中的cloudflared改成bore
cloudflare服务不稳定
此方法未验证，如果还有报错请告知我，谢谢

**Comment by physics1024** [comment]
已验证可以使用
